global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: 'pontim-app'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['host.docker.internal:3000']
