name: Build, Lint and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run lint
      run: npm run lint

    - name: Setup Prisma
      run: npx prisma generate

    - name: Setup Environment
      run: cp .env.example .env
    
    - name: Build
      run: npm run build --if-present
