name: Fly Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-it:
    uses: ./.github/workflows/release-it.yml
    secrets: inherit
    if: github.event_name != 'workflow_dispatch'

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: release-it
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy --remote-only \
            --build-secret NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
            --build-secret NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
            --build-secret DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-secret SITE_URL=${{ secrets.SITE_URL }} \
            --build-secret GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            --build-secret GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            --build-secret STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} \
            --build-secret STRIPE_PUBLISH_KEY=${{ secrets.STRIPE_PUBLISH_KEY }} \
            --build-secret STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }} \
            --build-secret FREE_PLAN_PRICE_ID=${{ secrets.FREE_PLAN_PRICE_ID }} \
            --build-secret RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
            --build-secret GA_ID=${{ secrets.GA_ID }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
