name: Deploy to EC2

on:
  workflow_run:
    workflows:
      - Build and Publish Docker Image
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo docker pull ${{ secrets.DOCKER_IMAGE }}

            sudo docker stop pontim || true
            sudo docker rm pontim || true

            sudo docker run --platform linux/amd64 -d --name pontim -p 80:3000 ${{ secrets.DOCKER_IMAGE }}

            sudo docker ps
            
            sudo docker image prune -f
          EOF
