name: Deploy Pontim

on: [workflow_call, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Copy docker-compose.yml to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "infra/docker-compose.yml"
          target: "~/pontim"

      - name: Ensure essential containers are running
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/pontim/infra

            REQUIRED_CONTAINERS=("redis" "prometheus" "grafana" "loki" "node-exporter" "nginx")

            for SERVICE in "${REQUIRED_CONTAINERS[@]}"; do
              CONTAINER_NAME="pontim-$SERVICE"
              if ! docker ps --filter "name=$CONTAINER_NAME" --filter "status=running" | grep -q "$CONTAINER_NAME"; then
                echo "🔁 $CONTAINER_NAME is not running. Starting..."
                docker compose up -d $SERVICE
              else
                echo "✅ $CONTAINER_NAME is already running."
              fi
            done
            echo "All required containers are running."
            docker ps

      - name: Run Pontim
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/pontim/infra

            echo "🔄 Updating pontim-app..."

            docker compose stop pontim
            docker compose rm -f pontim
            docker compose pull pontim
            docker compose up -d pontim

            echo "🚀 pontim-app updated!"
            docker ps