name: Deploy Pontim

on: [workflow_call, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Copy docker-compose.yml to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "infra/docker-compose.yml"
          target: "~/infra"

      - name: Check if Redis is running
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "Verificando se o Redis está rodando..."
            if ! docker ps --filter "name=pontim-redis" --filter "status=running" | grep "pontim-redis"; then
              echo "Redis is not running. Starting Redis..."
              docker-compose -f ~/infra/docker-compose.yml up -d redis
            else
              echo "Redis is already running."
            fi

      - name: Run Pontim
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/infra
            docker-compose pull pontim
            docker-compose up -d pontim
