name: Deploy to EC2

on: [workflow_call, workflow_dispatch]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo systemctl start docker

            sudo docker stop pontim
            sudo docker remove pontim

            sudo docker pull ${{ secrets.DOCKER_IMAGE }}

            sudo docker run --platform linux/arm64 --name pontim -p 80:3000 ${{ secrets.DOCKER_IMAGE }}

            sudo docker ps

            sudo docker logs pontim
            
            sudo docker image prune -f
          EOF
