name: Deploy Pontim

on: [workflow_call, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Copy docker-compose.yml to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "infra/docker-compose.yml"
          target: "~/pontim"

      - name: Check if Redis is running
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "Checking if Redis is running..."
            if ! docker ps --filter "name=pontim-redis" --filter "status=running" | grep "pontim-redis"; then
              echo "Redis is not running. Starting Redis..."
              docker compose -f ~/pontim/infra/docker-compose.yml up -d redis
              echo "Redis started."
              docker ps
            else
              echo "Redis is already running."
            fi

      - name: Run Pontim
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/pontim/infra
            
            echo "Pulling the latest image..."
            docker compose pull pontim-app
            
            echo "Stopping the current container..."
            docker compose stop pontim-app
            
            echo "Removing the current container..."
            docker compose rm -f pontim-app
            
            echo "Starting the new container..."
            docker compose up -d pontim-app

            echo "Current running containers:"
            docker ps
